### ISSUE TITLE
Background Hide Feature

### ISSUE THREAD

**Issue by montttera** [aneliyakarim/Doodle-App#3]
## Description
The current version of the Doodle App lacks the ability to hide the background while drawing. This enhancement suggests implementing a feature that allows users to **toggle the visibility of the background**, resulting in a clearer view of their drawings and facilitating corrections and improvements.

## Proposed Solution
The suggested solution is to provide users with an option to turn off the background, making the drawing more prominently visible. By hiding the background, users will have a better understanding of the areas that require corrections or adjustments. This feature can be implemented as a toggle button or a setting within the app's interface.

## Benefits: Improved visibility
By hiding the background, users will be able to **see their drawings more clearly** without the distraction of the background, making it easier for them to identify areas that need modification.

## Additional Considerations
- It would be beneficial to include **gestures** for conveniently toggling the background hide feature, ensuring a smooth and efficient user experience.

- Providing an option to **adjust the opacity** of the background when it is visible could be helpful for users who prefer a semi-transparent background.

**Comment by aneliyakarim** [comment]
@montttera 
Heeey Mario! Now the template's image can be hidden for the user's convenience. Thank you for your input! 🤩
